config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end
  
  authenticated :user do
    root 'groups#index', as: :authenticated_root
  end

  unauthenticated :user do
    root 'pages#splash', as: :unauthenticated_root
  end

  resources :groups, only: %i[index new create destroy] do
    resources :expenses, only: %i[index new create destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_and_belongs_to_many :groups

  validates :name, presence: true, length: { minimum: 3, maximum: 100 }
  validates :amount, numericality: { greater_than: 0 }

  after_create :add_total_expense

  before_destroy :subtract_total_expense

  private

  def add_total_expense
    groups.each { |category| category.update(total_expenses: (category.total_expenses + amount)) }
  end

  def subtract_total_expense
    groups.each { |category| category.update(total_expenses: (category.total_expenses - amount)) }
  end
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :expenses
  has_one_attached :icon

  validates :name, presence: true, length: { minimum: 3, maximum: 100 }
  validates :total_expenses, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }
  validates :icon, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :groups
  has_many :expenses, foreign_key: 'author_id'

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expense, only: %i[destroy]
  before_action :set_group

  # GET /expenses
  def index
    @expenses = @group.expenses
  end

  # GET /expenses/new
  def new
    @expense = Expense.new
  end

  # POST /expenses
  def create
    parameters = params.require(:expense).permit(:name, :amount, selected_groups: [])
    @expense = current_user.expenses.new(name: parameters[:name], amount: parameters[:amount])
    selected_groups = parameters[:selected_groups]
    groups = Group.where(id: selected_groups)
    groups.each do |group|
      @expense.groups.push(group)
    end

    respond_to do |format|
      if @expense.save
        format.html { redirect_to group_expenses_url(groups[0].id), notice: 'Expense was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1 or /expenses/1.json
  def destroy
    @expense.destroy
    respond_to do |format|
      format.html { redirect_to group_expenses_url(@group), notice: 'Expense was successfully destroyed.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_expense
    @expense = Expense.find(params[:id])
  end

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[show edit update destroy]

  # GET /groups or /groups.json
  def index
    @groups = current_user.groups.order(created_at: :desc)
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # POST /groups or /groups.json
  def create
    @group = current_user.groups.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to groups_url, notice: 'Category was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    Group.find(params[:id]).destroy

    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Category was successfully destroyed.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name, :total_expenses, :icon)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :splash
  def splash; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/expenses/_expense.html.erb
<div
  id="<%= dom_id expense %>"
  class="
    mx-4
    my-2
    p-5
    rounded-md
    bg-white
    flex
    items-center
    justify-between
  "
>
  <div class="flex flex-col space-y-2 h-full">
    <p class="text-2xl font-ProximaLight text-slate-600"><%= expense.name.capitalize %></p>
    <p class="text-xs text-DesignGray"><%= expense.created_at %></p>
  </div>
  <div class="flex flex-col space-y-2 items-center">
    <div class="flex items-center space-x-1">
      <span>$
        <%= expense.amount %></span>
    </div>
    <%= button_to "Delete", group_expense_path(@group.id, expense.id), class:"rounded-md p-1 bg-gray-200 inline-block text-xs transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 hover:bg-indigo-500 duration-300", method: :delete %>
  </div>
</div>

app/views/expenses/index.html.erb
<section
  id="expense"
  class="w-full min-h-screen bg-DesignWhite items-center flex flex-col"
>
  <header class="header-mob">
      <%= link_to :authenticated_root do %>
        <i class="fa fa-arrow-left link-hover"></i>
      <% end %>
    <h1 class='font-ProximaBold font-medium'><%=@group.name.capitalize%></h1>
    <i class="fa fa-search link-hover"></i>
  </header>
   <div
    class="
      flex
      w-full
      justify-between
      items-center
      p-4
      border-b-2
      bg-white
      text-sm
      mb-5
    "
  >
    <h1 class="text-ProximaLight text-DesignGray">Total Expenses</h1>
    <p>$ <%=@group.total_expenses%></p>
  </div>
  <p class="text-green-500"><%= notice %></p>
  <p class="text-red-500"><%= alert %></p>

    <div id="expenses" class="min-w-full flex flex-col">
      <%= render @expenses %>
    </div>
  </div>
   <div
    class="
      fixed
      z-10
      bottom-0
      flex
      items-center
      justify-center
      bg-DesignGreen
      w-full
      h-20
      px-5
      py-3
      text-white
      font-ProximaLight
      text-center
    "
  >
   <%= link_to 'New Expense', new_group_expense_path(group_id:@group.id), class:"text-xl flex items-center justify-center border-solid border-2 w-full h-full transition ease-in-out delay-150 hover:scale-y-110 duration-300" %>
   </div>
</section>

app/views/expenses/new.html.erb
<%= form_with(model: @expense, url: group_expenses_path(@group.id), class: "contents") do |form| %>
  <section
    id="new-expense"
    class="w-full min-h-screen bg-DesignWhite items-center flex flex-col"
  >
    <header class="header-mob mb-4">
      <%= link_to group_expenses_path(@group.id) do %>
        <i class="fa fa-arrow-left w-9 link-hover"></i>
      <% end %>
      <h1 class='font-ProximaBold font-medium'>New Expense</h1>
      <div class="actions">
        <%= form.submit "Create", class:'font-ProximaLight link-hover' %>
      </div>
    </header>
    <% if @expense.errors.any? %>
      <% @expense.errors.full_messages.each do |message| %>
        <h3 class="text-red-500"><%= message %>
        </h3>
      <% end %>
    <% end %>
    <p class="text-green-500"><%= notice %></p>
    <p class="text-red-500"><%= alert %></p>
    <div class="w-full flex flex-col border-2 border-gray-100">

      <div
        class="
          p-3
          w-full
          flex
          justify-center
          bg-white
          border-2
          border-gray-100
          items-center
          space-x-8
        "
      >
        <%= form.text_field :name, autofocus: true, autocomplete: "", placeholder: "Name", class:"placeholder:text-slate-500 border-gray-300 " %>
      </div>

      <div
        class="
          p-3
          w-full
          flex
          justify-center
          border-2
          border-gray-100
          bg-white
          items-center
          space-x-8
        "
      >
        <%= form.number_field :amount, placeholder:"Amount", class: "border-slate-300" %>
      </div>

      <div
        class="
          p-3
          pb-7
          w-full
          flex
          justify-center
          border-2
          border-gray-100
          bg-white
          items-center
        "
      >

        <%= form.select :selected_groups, current_user.groups.collect { |group| [group.name, group.id] }, { 
      disabled: "",:prompt => "Please Select your Categories"}, 
                                           { :multiple => true, :size => 5, :class=>"m-0 text-center flex flex-col space-y-3 border-gray-300"} %>
      </div>
    </div>
  </section>
<% end %>

app/views/groups/_group.html.erb
<div id="<%= dom_id group %>", class="mx-4 my-2 px-3 py-5 rounded-md bg-white flex items-center justify-between">
  <div class="flex space-x-3 items-center text-DesignGray">
  <% if group.icon.attached? %>
   <div class="object-cover h-20 w-16">
    <img src="<%= url_for(group.icon) %>", class="w-full h-full">
    </div>
  <% end %>
  <div class="flex flex-col space-y-2 h-full">
   <p><%= group.name %></p>
    <p class="text-xs"><%= group.created_at.strftime('%d %B %Y') %></p>
   </div>
   
  </div>


   <div class="flex flex-col space-y-3 items-center">
    <p class="text-center">$ <%= group.total_expenses %></p>
    <div class="flex space-x-2">         
    <%= button_to "Show", group_expenses_path(group.id), class:"rounded-md p-1 bg-gray-200 inline-block text-xs transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 hover:bg-indigo-500 duration-300", method: :get %>
    <%= button_to "Delete", group_path(group.id), class:"rounded-md p-1 bg-gray-200 inline-block text-xs transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 hover:bg-indigo-500 duration-300", method: :delete %>
    </div>

  </div>
</div>

app/views/groups/index.html.erb
<section
  id="group"
  class="w-full min-h-screen bg-DesignWhite items-center flex flex-col"
>
  <header class="header-mob z-10">
    <i class="fa fa-bars link-hover" id= "hamburger"></i>
    <h1 class='font-ProximaBold font-medium'>Categories</h1>
    <i class="fa fa-search link-hover"></i>
  </header>
  <div class="hidden mobile-menu fixed top-0 left-0 right-0 bg-DesignWhite w-1/2 sm:w-80 p-5 py-12">
    <ul class="space-y-4 flex flex-col items-center">
      <li>    
      <%= image_tag "budget.svg", width:"300", class:"mt-auto" %>

      </li>
      <li class="
            text-sm
           link-hover text-ProximaLight italic text-orange-400 cursor-default"><%= current_user.name%>
      <li class="rounded-md p-1 bg-gray-200 inline-block text-xs transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 hover:bg-indigo-500 duration-300"><%= link_to "Log out",'/users/sign_out'%></li>
    </ul>
  </div>
  <div
    class="
      flex
      w-full
      justify-between
      items-center
      p-4
      border-b-2
      bg-white
      text-sm
      mb-5
    "
  >
    <h1 class="text-ProximaLight text-DesignGray">Gift credit</h1>
    <p>$ 0</p>
  </div>
  <p class="text-green-500"><%= notice %></p>
  <p class="text-red-500"><%= alert %></p>
  <div id="groups" class="min-w-full flex flex-col">
    <%= render @groups %>
  </div>
  <div
    class="
      fixed
      z-10
      bottom-0
      flex
      items-center
      justify-center
      bg-DesignGreen
      w-full
      h-20
      px-5
      py-3
      text-white
      font-ProximaLight
      text-center
    "
  >
    <%= link_to 'New Category', new_group_path, class:"text-xl flex items-center justify-center border-solid border-2 w-full h-full transition ease-in-out delay-150 hover:scale-y-110 duration-300" %>
  </div>
 <%= javascript_include_tag 'navbar' %>
</section>

app/views/groups/new.html.erb
<%= form_with(model: @group, class: "contents") do |form| %>
  <section
    id="new-group"
    class="w-full min-h-screen bg-DesignWhite items-center flex flex-col"
  >
    <header class="header-mob mb-4">
      <%= link_to groups_path do %>
        <i class="fa fa-arrow-left w-9 link-hover"></i>
      <% end %>
      <h1 class='font-ProximaBold font-medium'>NEW CATEGORY</h1>
      <div class="actions">
        <%= form.submit "Create", class:'font-ProximaLight link-hover' %>
      </div>
    </header>
    <% if @group.errors.any? %>
      <% @group.errors.full_messages.each do |message| %>
        <h3 class="text-red-500"><%= message %>
        </h3>
      <% end %>
    <% end %>
    <p class="text-green-500"><%= notice %></p>
    <p class="text-red-500"><%= alert %></p>
    <div class="w-full flex flex-col ">
      <div class="field">
        <%= form.text_field :name, autofocus: true, autocomplete: "", placeholder: "Name", class:"placeholder:text-slate-400 w-full border-gray-100 " %>
      </div>

      <div class="field p-3 bg-white items-center space-x-3">
        <%= form.label :icon, class:"text-slate-400" %>
        <%= form.file_field :icon, accept:"image/png, image/gif, image/jpeg, image/svg, image/jpg", class: "flex items-center shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full text-ProximaLight" %>
      </div>
    </div>
  </section>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/splash.html.erb
<section
  id="splash"
  class="
    w-full
    min-h-screen
    justify-center
    items-center
    flex
    flex-col
    bg-DesignWhite
  "
>
  <%= image_tag "budget.svg", width:"400", class:"mt-auto" %>
  <div class="mt-auto flex flex-col items-center w-full space-y-5 mb-8">
    <%= link_to "LOG IN", new_user_session_path, class:"flex items-center justify-center bg-DesignBlue w-4/5 h-12 text-white font-ProximaLight text-center sm:max-w-sm button-hover" %>
    <%= link_to "SIGN UP", new_user_registration_path, class:"link-hover" %>
  </div>
</section>